<div class="breadcrumb">
	<a href="">Home</a> 
	<a href="">Products</a> 
	<a href="">Iphone 6</a>
</div>
<div class="content">
	<div class="panel">
		<div class="content-header no-mg-top">
			<i class="fa fa-newspaper-o"></i>
			<div class="content-header-title">Batch Icon Icons</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="content-box">
					<div class="icon-list-wrapper">
						<div id="web-application">
							<div class="row">
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-add" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-add</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-add" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-add</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-address-book-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-address-book-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-address-book" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-address-book</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-alarm-clock" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-alarm-clock</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-align-bottom" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-align-bottom</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-align-horizontal-centers" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-align-horizontal-centers</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-align-left-edges" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-align-left-edges</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-align-right-edges" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-align-right-edges</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-align-top" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-align-top</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-align-vertical-centers" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-align-vertical-centers</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-anchor" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-anchor</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-arrow-down" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-arrow-down</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-arrow-left" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-arrow-left</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-arrow-right" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-arrow-right</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-arrow-up" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-arrow-up</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-asterisk" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-asterisk</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-attachment-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-attachment-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-attachment" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-attachment</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-audio-high" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-audio-high</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-audio-low" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-audio-low</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-audio-mid" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-audio-mid</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-audio-mute" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-audio-mute</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-battery-20-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-battery-20-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-battery-20" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-battery-20</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-battery-40-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-battery-40-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-battery-40" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-battery-40</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-battery-60-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-battery-60-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-battery-60" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-battery-60</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-battery-80-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-battery-80-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-battery-80" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-battery-80</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-battery-100-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-battery-100-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-battery-100" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-battery-100</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-battery-charge-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-battery-charge-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-battery-charge" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-battery-charge</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-battery-empty-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-battery-empty-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-battery-empty" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-battery-empty</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-bell-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-bell-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-bell-mute-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-bell-mute-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-bell-mute" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-bell-mute</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-bell" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-bell</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-bin-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-bin-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-bin-3" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-bin-3</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-bin" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-bin</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-book-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-book-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-book-lines-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-book-lines-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-book-lines" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-book-lines</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-book" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-book</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-brightness-high" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-brightness-high</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-brightness-low" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-brightness-low</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-browser-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-browser-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-browser-close-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-browser-close-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-browser-close" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-browser-close</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-browser-download-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-browser-download-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-browser-download" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-browser-download</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-browser-minimize-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-browser-minimize-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-browser-minimize" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-browser-minimize</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-browser-new-window-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-browser-new-window-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-browser-new-window" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-browser-new-window</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-browser-upload-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-browser-upload-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-browser-upload" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-browser-upload</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-browser-windows-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-browser-windows-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-browser-windows" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-browser-windows</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-browser" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-browser</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-bulb-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-bulb-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-bulb" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-bulb</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-bullet" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-bullet</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-bullhorn-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-bullhorn-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-bullhorn" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-bullhorn</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-calendar" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-calendar</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-camera-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-camera-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-camera-3" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-camera-3</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-camera" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-camera</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-cassette" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-cassette</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-clipboard-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-clipboard-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-clipboard" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-clipboard</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-clock" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-clock</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-cloud-add-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-cloud-add-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-cloud-add" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-cloud-add</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-cloud-download" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-cloud-download</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-cloud-remove-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-cloud-remove-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-cloud-remove" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-cloud-remove</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-cloud-upload" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-cloud-upload</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-cloud" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-cloud</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-cmd" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-cmd</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-code" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-code</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-commit" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-commit</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-compass" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-compass</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-compose-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-compose-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-compose-3" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-compose-3</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-compose-4" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-compose-4</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-compose" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-compose</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-contract-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-contract-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-contract-3" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-contract-3</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-contract" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-contract</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-contrast" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-contrast</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-converge" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-converge</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-crate" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-crate</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-credit-card-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-credit-card-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-credit-card-3" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-credit-card-3</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-credit-card-4" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-credit-card-4</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-credit-card" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-credit-card</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-crop" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-crop</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-cross" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-cross</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-curlybrace-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-curlybrace-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-curlybrace" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-curlybrace</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-database-add" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-database-add</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-database-remove" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-database-remove</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-database" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-database</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-delete" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-delete</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-distribute-bottom-edges" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-distribute-bottom-edges</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-distribute-horizontal-centers" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-distribute-horizontal-centers</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-distribute-left-edges" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-distribute-left-edges</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-distribute-right-edges" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-distribute-right-edges</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-distribute-top-edges" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-distribute-top-edges</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-distribute-vertical-centers" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-distribute-vertical-centers</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-document-add" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-document-add</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-document-remove" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-document-remove</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-document" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-document</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-droplet" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-droplet</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-ellipsis" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-ellipsis</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-envelope" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-envelope</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-exclude" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-exclude</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-expand-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-expand-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-expand-3" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-expand-3</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-expand" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-expand</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-eye-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-eye-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-eye" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-eye</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-fast-forward" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-fast-forward</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-flag-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-flag-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-flag" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-flag</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-flask-empty" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-flask-empty</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-flask-full" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-flask-full</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-floppy" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-floppy</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-flux" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-flux</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-folder-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-folder-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-folder-add-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-folder-add-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-folder-add" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-folder-add</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-folder-duplicate-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-folder-duplicate-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-folder-duplicate" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-folder-duplicate</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-folder-remove-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-folder-remove-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-folder-remove" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-folder-remove</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-folder" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-folder</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-fork" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-fork</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-grid-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-grid-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-grid" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-grid</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-headphones" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-headphones</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-heart-empty" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-heart-empty</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-heart-full" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-heart-full</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-heart-half" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-heart-half</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-home-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-home-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-home-3" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-home-3</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-home" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-home</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-icon0" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-icon0</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-image" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-image</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-in" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-in</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-inbox-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-inbox-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-inbox" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-inbox</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-infinity" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-infinity</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-intersect" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-intersect</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-key-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-key-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-key" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-key</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-keys" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-keys</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-layout-column-center" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-layout-column-center</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-layout-content-left-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-layout-content-left-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-layout-content-left" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-layout-content-left</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-layout-content-right-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-layout-content-right-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-layout-content-right" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-layout-content-right</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-layout-sidebar-left" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-layout-sidebar-left</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-layout-sidebar-right" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-layout-sidebar-right</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-link-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-link-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-link" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-link</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-list-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-list-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-list" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-list</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-locked" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-locked</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-mail-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-mail-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-mail-3" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-mail-3</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-mail-4" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-mail-4</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-mail-incoming" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-mail-incoming</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-mail-outgoing" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-mail-outgoing</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-mail" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-mail</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-map-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-map-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-map" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-map</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-marquee-download" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-marquee-download</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-marquee-minus" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-marquee-minus</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-marquee-plus" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-marquee-plus</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-marquee-upload" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-marquee-upload</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-marquee" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-marquee</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-maximise" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-maximise</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-menu-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-menu-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-menu-pull-down" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-menu-pull-down</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-menu-pull-up" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-menu-pull-up</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-menu" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-menu</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-microphone-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-microphone-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-microphone" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-microphone</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-minus" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-minus</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-mixer" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-mixer</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-newspaper-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-newspaper-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-newspaper" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-newspaper</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-next" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-next</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-nib" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-nib</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-nope" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-nope</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-notes" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-notes</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-options" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-options</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-out" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-out</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-outbox-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-outbox-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-outbox" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-outbox</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-outgoing-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-outgoing-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-outgoing" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-outgoing</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-paper-ripped" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-paper-ripped</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-paper-roll-ripped" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-paper-roll-ripped</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-paper-roll" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-paper-roll</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-paragraph-center-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-paragraph-center-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-paragraph-center" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-paragraph-center</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-paragraph-justify-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-paragraph-justify-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-paragraph-justify" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-paragraph-justify</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-paragraph-left-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-paragraph-left-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-paragraph-left" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-paragraph-left</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-paragraph-right-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-paragraph-right-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-paragraph-right" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-paragraph-right</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-pause" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-pause</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-pen" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-pen</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-pencil" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-pencil</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-pin-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-pin-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-pin" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-pin</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-play" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-play</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-plus" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-plus</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-podcast-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-podcast-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-podcast" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-podcast</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-polaroid-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-polaroid-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-polaroid" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-polaroid</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-power" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-power</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-previous" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-previous</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-print" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-print</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-pull" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-pull</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-quill-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-quill-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-quill" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-quill</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-refresh" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-refresh</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-reminder" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-reminder</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-remove" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-remove</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-repeat-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-repeat-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-repeat" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-repeat</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-reply-all" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-reply-all</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-reply" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-reply</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-return" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-return</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-revert" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-revert</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-rewind" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-rewind</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-rulers" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-rulers</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-safe" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-safe</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-search-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-search-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-search" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-search</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-section" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-section</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-settings-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-settings-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-settings-3" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-settings-3</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-settings-4" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-settings-4</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-settings" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-settings</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-shred" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-shred</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-shuffle" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-shuffle</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-sleep" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-sleep</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-spam-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-spam-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-spam" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-spam</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-speech-bubble-center-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-speech-bubble-center-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-speech-bubble-center-3" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-speech-bubble-center-3</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-speech-bubble-center" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-speech-bubble-center</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-speech-bubble-left-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-speech-bubble-left-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-speech-bubble-left-3" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-speech-bubble-left-3</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-speech-bubble-left-4" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-speech-bubble-left-4</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-speech-bubble-left" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-speech-bubble-left</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-speech-bubble-right-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-speech-bubble-right-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-speech-bubble-right-3" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-speech-bubble-right-3</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-speech-bubble-right-4" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-speech-bubble-right-4</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-speech-bubble-right" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-speech-bubble-right</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-spinner-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-spinner-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-spinner-3" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-spinner-3</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-spinner" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-spinner</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-split-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-split-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-split" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-split</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-spool" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-spool</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-square-brackets" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-square-brackets</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-stamp-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-stamp-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-stamp" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-stamp</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-star-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-star-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-star" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-star</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-stiffy" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-stiffy</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-stop" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-stop</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-stopwatch" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-stopwatch</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-store-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-store-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-store" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-store</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-subtract" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-subtract</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-support-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-support-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-support-3" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-support-3</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-support" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-support</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-swap-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-swap-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-swap" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-swap</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-swatch" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-swatch</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-swatches" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-swatches</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-switch-off" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-switch-off</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-switch-on" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-switch-on</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-tag-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-tag-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-tag-3" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-tag-3</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-tag-4" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-tag-4</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-tag" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-tag</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-terminal-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-terminal-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-terminal-3" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-terminal-3</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-terminal" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-terminal</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-tick" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-tick</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-tilde" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-tilde</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-timeline" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-timeline</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-toggle-off" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-toggle-off</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-toggle-on" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-toggle-on</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-transfer" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-transfer</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-tray" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-tray</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-unite" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-unite</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-unlocked" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-unlocked</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-unwatch" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-unwatch</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-user-2-add" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-user-2-add</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-user-2-remove" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-user-2-remove</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-user-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-user-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-user-3" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-user-3</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-user-4-add" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-user-4-add</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-user-4-remove" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-user-4-remove</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-user-4" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-user-4</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-user-card" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-user-card</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-user" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-user</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-users" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-users</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-video-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-video-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-video" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-video</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-vinyl" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-vinyl</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-voicemail" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-voicemail</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-wallet-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-wallet-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-wallet" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-wallet</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-watch-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-watch-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-watch" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-watch</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-wave-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-wave-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-wave" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-wave</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-wifi-high" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-wifi-high</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-wifi-low" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-wifi-low</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-wifi-mid" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-wifi-mid</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-wiggle" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-wiggle</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-windows" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-windows</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-zoom-in-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-zoom-in-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-zoom-in" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-zoom-in</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-zoom-out-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-zoom-out-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="batch-icon-zoom-out" aria-hidden="true"></i> <span class="sr-only">Example of </span>batch-icon-zoom-out</a></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>