<div class="breadcrumb">
	<a href="">Home</a> 
	<a href="">Products</a> 
	<a href="">Iphone 6</a>
</div>
<div class="content">
	<div class="panel">
		<div class="content-header no-mg-top">
			<i class="fa fa-newspaper-o"></i>
			<div class="content-header-title">Metrize Icons</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="content-box">
					<div class="icon-list-wrapper">
						<div id="web-application">
							<div class="row">
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-yen" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-yen</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-world" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-world</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-wireframe-globe" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-wireframe-globe</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-wind" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-wind</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-wifi" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-wifi</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-waves" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-waves</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-viewport" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-viewport</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-viewport-video" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-viewport-video</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-user" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-user</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-user-remove" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-user-remove</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-user-ban" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-user-ban</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-user-add" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-user-add</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-upload" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-upload</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-upload-selection" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-upload-selection</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-upload-selection-circle" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-upload-selection-circle</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-underline" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-underline</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-triple-points" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-triple-points</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-top-bottom" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-top-bottom</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-three-points" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-three-points</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-three-points-top" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-three-points-top</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-three-points-bottom" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-three-points-bottom</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-text-width" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-text-width</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-text-size-upper" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-text-size-upper</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-text-size-reduce" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-text-size-reduce</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-text-paragraph" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-text-paragraph</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-text-normal" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-text-normal</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-text-justify-right" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-text-justify-right</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-text-justify-left" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-text-justify-left</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-text-justify-center" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-text-justify-center</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-text-height" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-text-height</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-text-center" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-text-center</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-text-bold" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-text-bold</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-text-align-right" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-text-align-right</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-text-align-left" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-text-align-left</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-telephone" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-telephone</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-sunshine" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-sunshine</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-sun" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-sun</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-stop" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-stop</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-star" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-star</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-speed" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-speed</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-sound-on" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-sound-on</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-sound-off" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-sound-off</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-sos" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-sos</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-zerply" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-zerply</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-youtube" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-youtube</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-yelp" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-yelp</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-yahoo" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-yahoo</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-wordpress" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-wordpress</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-virb" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-virb</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-vimeo" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-vimeo</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-viddler" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-viddler</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-twitter" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-twitter</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-tumblr" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-tumblr</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-stumbleupon" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-stumbleupon</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-soundcloud" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-soundcloud</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-skype" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-skype</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-sharethis" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-sharethis</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-quora" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-quora</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-pinterest" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-pinterest</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-photobucket" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-photobucket</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-paypal" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-paypal</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-myspace" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-myspace</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-linkedin" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-linkedin</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-last-fm" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-last-fm</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-grooveshark" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-grooveshark</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-google-plus" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-google-plus</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-github" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-github</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-forrst" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-forrst</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-flickr" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-flickr</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-facebook" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-facebook</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-evernote" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-evernote</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-envato" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-envato</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-email" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-email</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-dribbble" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-dribbble</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-digg" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-digg</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-deviantart" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-deviantart</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-blogger" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-blogger</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-behance" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-behance</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-bebo" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-bebo</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-addthis" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-addthis</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-social-500px" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-social-500px</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-snow" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-snow</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-sliders" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-sliders</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-sliders-vertical" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-sliders-vertical</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-sign-male" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-sign-male</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-sign-female" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-sign-female</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-shield" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-shield</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-settings" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-settings</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-setting" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-setting</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-select-square" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-select-square</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-select-circle" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-select-circle</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-search" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-search</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-scale" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-scale</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-rules" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-rules</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-rss" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-rss</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-retweet" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-retweet</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-report-comment" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-report-comment</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-refresh" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-refresh</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-rec" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-rec</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-random" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-random</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-quote" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-quote</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-question" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-question</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-previous-fast-step" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-previous-fast-step</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-prev-step" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-prev-step</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-pounds" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-pounds</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-podcast" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-podcast</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-plus" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-plus</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-play" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-play</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-pin" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-pin</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-pin-map" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-pin-map</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-pig-money" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-pig-money</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-pause" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-pause</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-paperclip" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-paperclip</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-paperclip-oblique" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-paperclip-oblique</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-options-settings" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-options-settings</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-officine" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-officine</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-officine-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-officine-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-off" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-off</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-number-zero" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-number-zero</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-number-two" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-number-two</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-number-three" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-number-three</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-number-six" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-number-six</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-number-seven" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-number-seven</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-number-one" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-number-one</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-number-nine" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-number-nine</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-number-four" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-number-four</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-number-five" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-number-five</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-number-eight" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-number-eight</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-next-step" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-next-step</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-next-fast-step" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-next-fast-step</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-music" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-music</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-multi-borders" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-multi-borders</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-minus" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-minus</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-marker" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-marker</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-marker-points" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-marker-points</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-marker-minus" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-marker-minus</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-marker-add" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-marker-add</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-map" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-map</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-male-symbol" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-male-symbol</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-mailbox" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-mailbox</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-mail" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-mail</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-magnet" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-magnet</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-magic-wand" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-magic-wand</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-login-lock-refresh" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-login-lock-refresh</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-locked" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-locked</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-location" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-location</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-location-maps" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-location-maps</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-list-square" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-list-square</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-list-circle" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-list-circle</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-link-url" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-link-url</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-line-through" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-line-through</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-limit-directions" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-limit-directions</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-like-upload" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-like-upload</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-like-remove" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-like-remove</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-like-download" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-like-download</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-like-close" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-like-close</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-like-ban" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-like-ban</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-like-add" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-like-add</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-left-right" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-left-right</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-leaf" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-leaf</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-layers" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-layers</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-landscape" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-landscape</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-key" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-key</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-italic" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-italic</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-info" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-info</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-idea" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-idea</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-home-wifi" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-home-wifi</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-heart" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-heart</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-hdd" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-hdd</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-hdd-raid" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-hdd-raid</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-hdd-net" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-hdd-net</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-grids" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-grids</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-grid-big" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-grid-big</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-graphs" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-graphs</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-forward" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-forward</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-fire" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-fire</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-female-symbol" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-female-symbol</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-eye" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-eye</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-eye-disabled" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-eye-disabled</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-expand" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-expand</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-expand-vertical" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-expand-vertical</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-expand-horizontal" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-expand-horizontal</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-expand-directions" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-expand-directions</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-exclamation" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-exclamation</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-euro" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-euro</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-email-upload" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-email-upload</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-email-spam" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-email-spam</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-email-remove" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-email-remove</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-email-luminosity" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-email-luminosity</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-email-download" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-email-download</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-email-close" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-email-close</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-email-add" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-email-add</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-eject" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-eject</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-drops" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-drops</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-drop" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-drop</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-download" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-download</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-download-selection" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-download-selection</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-download-selection-circle" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-download-selection-circle</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-double-diamonds" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-double-diamonds</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-dot-square" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-dot-square</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-dot-line" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-dot-line</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-dot-circle" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-dot-circle</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-dollar" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-dollar</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-documents" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-documents</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-document" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-document</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-document-fill" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-document-fill</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-directions" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-directions</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-cross" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-cross</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-credit-card" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-credit-card</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-copy-paste-document" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-copy-paste-document</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-copy-document" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-copy-document</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-contract-vertical" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-contract-vertical</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-contract-horizontal" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-contract-horizontal</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-contract-directions" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-contract-directions</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-compass" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-compass</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-compass-2" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-compass-2</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-comments" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-comments</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-comment" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-comment</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-coins" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-coins</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-cloud" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-cloud</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-cloud-upload" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-cloud-upload</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-cloud-remove" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-cloud-remove</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-cloud-download" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-cloud-download</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-cloud-add" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-cloud-add</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-clock" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-clock</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-circles" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-circles</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-check" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-check</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-chat" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-chat</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-chart-down" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-chart-down</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-cd-dvd-rom" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-cd-dvd-rom</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-camera" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-camera</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-button-question" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-button-question</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-button-minus" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-button-minus</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-button-exclamation" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-button-exclamation</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-button-email" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-button-email</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-button-close" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-button-close</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-button-check" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-button-check</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-button-add" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-button-add</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-brush" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-brush</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-browser-sizes" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-browser-sizes</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-box-remove" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-box-remove</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-box-close" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-box-close</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-box-blank" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-box-blank</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-box-add" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-box-add</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-bolt" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-bolt</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-block-menu" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-block-menu</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-blank" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-blank</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-bezier" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-bezier</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-bars" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-bars</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-ban-circle" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-ban-circle</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-bag" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-bag</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-backward" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-backward</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-axis-rules" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-axis-rules</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-atom" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-atom</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-up" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-up</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-up-thin" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-up-thin</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-up-light" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-up-light</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-up-bold" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-up-bold</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-up-bold-round" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-up-bold-round</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-up-big" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-up-big</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-right" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-right</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-right-thin" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-right-thin</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-right-light" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-right-light</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-right-bold" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-right-bold</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-right-bold-round" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-right-bold-round</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-right-big" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-right-big</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-oblique-expand" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-oblique-expand</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-oblique-expand-directions" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-oblique-expand-directions</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-oblique-contract" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-oblique-contract</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-oblique-contract-directions" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-oblique-contract-directions</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-multi-line-up" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-multi-line-up</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-multi-line-right" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-multi-line-right</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-multi-line-left" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-multi-line-left</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-multi-line-down" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-multi-line-down</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-left" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-left</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-left-thin" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-left-thin</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-left-light" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-left-light</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-left-bold" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-left-bold</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-left-bold-round" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-left-bold-round</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-left-big" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-left-big</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-fill-up" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-fill-up</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-fill-right" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-fill-right</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-fill-left" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-fill-left</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-fill-down" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-fill-down</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-down" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-down</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-down-thin" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-down-thin</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-down-light" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-down-light</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-down-bold" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-down-bold</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-down-bold-round" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-down-bold-round</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-down-big" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-down-big</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-cycling" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-cycling</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-cycle" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-cycle</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-curve-right" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-curve-right</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-curve-recycle" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-curve-recycle</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-arrow-curve-left" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-arrow-curve-left</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-animal-footprint" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-animal-footprint</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-alarm-clock" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-alarm-clock</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-air-plane" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-air-plane</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-adjust" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-adjust</a></div>
								<div class="fa-hover col-md-3 col-sm-4"><a href="../icon/address-book"><i class="icon-cube" aria-hidden="true"></i> <span class="sr-only">Example of </span>icon-cube</a></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>